Some new features (-hostaudio, -quiet) and cleanup as usual.
Add -hostaudio to try starting and using pulseaudio on the host for
guest audio.

Add -quiet/-q/-silence/-s for the script to be quiet unless there's a
problem. Some prints have had a "fault" argument added to squeeze
through the flag when there's a problem.

diff --git a/main b/main
--- a/main
+++ b/main
@@ -44,6 +44,10 @@ fi
 #|_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 # 
 
+function printer {
+  if [ -z "$quiet" ] || [ "$2" == "fault" ] ; then echo -e "${@} ${colors[none]}" ; fi
+}
+
 function printHelp {
   printer "This script exists to make various vfio activity less convoluted. Among other use-cases"
   printer "such as LiveCD usage, testing if drives boot, PXE imaging, or any thing else with optional PCI passthrough."
@@ -81,6 +85,10 @@ function printHelp {
   printer "    Enable hyper-v enlightenments for nested virtualization."
   printer "    Can help invasive anticheats play along however HyperV will need to be enabled in the guest's Features.\n"
 
+  printer "  ${colors[cyan]}-hostaudio"
+  printer "    Enable an audiodev for VM audio to go through the host's pulseaudio server."
+  printer "    Will fail if pulseaudio is not installed on the host.\n"
+
   printer "  ${colors[cyan]}-usb 'SteelSeries|Keyboard|Xbox|1234:5678'"
   printer "    A regex for lsusb parsing. Matches against device lines from lsusb output.\n"
 
@@ -101,12 +109,11 @@ function printHelp {
   printer "    (Setting this also shapes the guest CPU topology to match.)"
   printer "    If you've configured core isolation on the host, this is the argument for you!\n"
 
+  printer "  ${colors[cyan]}-quiet/-q/-silence/-s"
+  printer "    Try to be quiet, only print if we have an error.\n"
+
   printer "Please see the README.md file for more information about the flags."
   exit 1
-}
-
-function printer {
-  echo -e "${@} ${colors[none]}"
 }
 
 function permissionsManager { # chown's things before qemu starts, but also tries to return them in the end.
@@ -150,15 +157,14 @@ function gpuCheck { if grep -o '\[VGA controller\]' <<<$(lspci -vnnn -s "$1") > 
 
 function bindingTimeout {
   if [ ! -z "$1" ]; then attemptedTask=$1 ; else attemptedTask="bind or unbind" ; fi
-  printer "${colors[red]}    The device  $fullBuspath ${colors[red]}// $vendorClass ${colors[red]} Was unable to $attemptedTask after 5 seconds, is something else using it? (E.g This will happen to a GPU in use by X). Giving up."
+  printer "${colors[red]}    The device  $fullBuspath ${colors[red]}// $vendorClass ${colors[red]} Was unable to $attemptedTask after 5 seconds, is something else using it? (E.g This will happen to a GPU in use by X). Giving up." "fault"
   exit 1
 }
 
   # Try to undo any mess we've caused at the end of a run
 function do_cleanup {
-  echo "Cleaning up.."
+  printer "\n${colors[yellow]}Cleaning up.."
   permissionsManager return # Restore original permissions if any
-  echo -ne ""
   if ! isDry
   then
       # Undo bridge if used
@@ -179,7 +185,7 @@ function do_cleanup {
     fi
   fi
   [ -f '/dev/shm/looking-glass' ] && rm /dev/shm/looking-glass
-  printer "\n${colors[green]}Cleanup complete."
+  printer "${colors[green]}Cleanup complete."
   exit
 }
 
@@ -202,8 +208,8 @@ function bridger {
   then
     if [ ! -z "$int" ]
     then
-      if [ ! -d /sys/class/net/$int ]      ; then printer "${colors[green]}interface $int specified but not found, not bridging."              ; brStartFault=1 ; exit 1 ; else intExists=1 ; fi
-      if [ -L /sys/class/net/$int/master ] ; then printer "${colors[red]}interface $int specified but already part of a bridge, not changing." ; brStartFault=1 ; exit 1 ; fi
+      if [ ! -d /sys/class/net/$int ]      ; then printer "${colors[red]}interface $int specified but not found, not bridging." "fault"                ; brStartFault=1 ; exit 1 ; else intExists=1 ; fi
+      if [ -L /sys/class/net/$int/master ] ; then printer "${colors[red]}interface $int specified but already part of a bridge, not changing." "fault" ; brStartFault=1 ; exit 1 ; fi
     else
       printer "Host int not specified, will attach VM tap to existing bridge"
       intExists=0
@@ -229,7 +235,7 @@ function bridger {
       printer "${colors[green]}bridge $br not found while host int specified, will create $br for this session and attach $int + $tap to it."
       bridgePreexists=0
     else
-      printer "${colors[red]}bridge $br not found but no host int specified to bridge VM with. Refusing to create bridge with no host interface."
+      printer "${colors[red]}bridge $br not found but no host int specified to bridge VM with. Refusing to create bridge with no host interface." "fault"
       brStartFault=1
       exit 1
     fi
@@ -318,27 +324,27 @@ function enumerateUSBs { # Generate usb related arguments for the guest.
 
 function enumeratePCIs { # This makes arguments and also unbinds from drivers. Optional vfio-pci rebinding.
   function gpuDetectedAndInUse {
-    printer "${colors[yellow]}    Video device $1 is bound to a driver which isn't vfio-pci and could be in use by the DM, framebuffer or otherwise."
-    printer "${colors[yellow]}    For this reason the script will now attempt to stop the display-manager service and unbind "
-    printer "${colors[yellow]}    the efi framebuffer instead of risking a driver unbind deadlock in waiting for X to quit."
-    printer "${colors[yellow]}    If your X server and virtual consoles don't use this card you can unbind it from its driver manually before running this script."
+    printer "${colors[yellow]}    Video device $1 is bound to a driver which isn't vfio-pci and could be in use by the DM, framebuffer or otherwise." "fault"
+    printer "${colors[yellow]}    For this reason the script will now attempt to stop the display-manager service and unbind" "fault"
+    printer "${colors[yellow]}    the efi framebuffer instead of risking a driver unbind deadlock in waiting for X to quit." "fault"
+    printer "${colors[yellow]}    If your X server and virtual consoles don't use this card you can unbind it from its driver manually before running this script." "fault"
     if systemctl is-active display-manager >/dev/null && ! isDry
     then
-      printer "${colors[yellow]}    Stopping display-manager and unbinding console drivers in 5 seconds..." ; sleep 5
+      printer "${colors[yellow]}    Stopping display-manager and unbinding console drivers in 5 seconds..." "fault"; sleep 5
       sudo systemctl stop display-manager ; export dm="seen"
     else
-      printer "${colors[yellow]}    Could not find a service for display-manager. Confused but trying to continue anyway."
+      printer "${colors[yellow]}    Could not find a service for display-manager. Confused but trying to continue anyway." "fault"
     fi
     consoleDrivers unbind
   }
 
-  echo "PCI:"
+  printer "PCI:"
   declare -A -g deviceDrivers # Array for tracking devices and their driver.
   if ! lsmod|grep -q vfio_pci;
   then
     printer "${colors[yellow]}  vfio-pci isn't loaded. Loading it now."
     sudo modprobe vfio-pci
-    if [ "$?" -ne "0" ]; then printer "${colors[red]}  Could not modprobe vfio-pci. Please fix this."; exit 1 ; fi
+    if [ "$?" -ne "0" ]; then printer "${colors[red]}  Could not modprobe vfio-pci. Please fix this." "fault"; exit 1 ; fi
   fi
 
   lspciOutput="$(lspci -nn)" ; PCIDevices="$(grep -E "$pciREGEX" <<<"$lspciOutput")"
@@ -371,7 +377,7 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
           printer "    [INFO] ${colors[green]}Detected driver ${driver}${colors[green]} is using this device. It will be re-bound on VM exit."
         fi
       else
-        printer "    [INFO] ${colors[green]}Has no driver, it will be bound to vfio-pci and left that way for the remainder of this boot."
+        printer "    [INFO] ${colors[green]}Has no driver, it will be bound to vfio-pci and will be left that way."
       fi
     fi
 
@@ -408,7 +414,7 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
       while ! [ -c /dev/vfio/$iommuGroup ]
       do
         sleep 1 && ((++iommuTimeout))
-	if [ $iommuTimeout -gt 5 ]; then printer "${colors[red]}    Timed out waiting for bound device to appear under /dev/vfio" ; exit 1 ; fi
+	if [ $iommuTimeout -gt 5 ]; then printer "${colors[red]}    Timed out waiting for bound device to appear under /dev/vfio" "fault" ; exit 1 ; fi
       done
       permissionsManager takeown /dev/vfio/${iommuGroup}
       echo 1 | sudo tee /sys/bus/pci/rescan >/dev/null
@@ -424,9 +430,9 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
         echo "0x$vendor 0x$class" | sudo tee /sys/bus/pci/drivers/vfio-pci/remove_id >/dev/null &2>&1
 	echo "$fullBuspath" | sudo tee /sys/bus/pci/devices/$fullBuspath/driver/unbind       > /dev/null
 	echo "$fullBuspath" | sudo tee /sys/bus/pci/drivers/$driver/bind                 > /dev/null
-	if [ "$?" -eq "0" ]; then printer "${colors[green]}    Successfully rebound." ; else printer "${colors[red]}    Was unable to rebind it to $driver."; fi
+	if [ "$?" -eq "0" ]; then printer "${colors[green]}    Successfully rebound." ; else printer "${colors[red]}    Was unable to rebind it to $driver." "fault"; fi
       else
-        printer "${colors[green]}    Device $vendorClass had no driver so left bound to vfio-pci."
+        printer "${colors[green]}    Device $vendorClass had no driver so it has been left bound to vfio-pci."
       fi
     fi
 
@@ -465,7 +471,7 @@ function pinVcpus {
 	printer "${colors[yellow]}Waiting for vcpus to wake up... $foundVcpus found." >&2
         sleep 1 
       done 
-    if [ $timer -eq $timeout ] ; then printer "${colors[red]}The vcpus did not wake up in time. This will happen on large qemu launches or slower systems but pinning failed." >&2 ; fi
+    if [ $timer -eq $timeout ] ; then printer "${colors[red]}The vcpus did not wake up in time. This will happen on large qemu launches or slower systems but pinning failed." "fault" >&2 ; fi
       
     threadPinList=$(for child in /proc/$1/task/* ; do if grep -q CPU $child/comm; then echo $(basename $child) ; fi ; done)
     printer "Successfully found $(wc -l <<< $threadPinList) vCPUs on the guest." >&2
@@ -502,6 +508,9 @@ do
     ;;
     -nocolor|-nocolors|-nocolor|-nocolors)
        unset colors # Pretty simple color killer.
+    ;;
+    -quiet|-q|-silence|-s)
+       quiet=1 # The printer function looks for this
     ;;
     -iommugroups|-iommugrouping)
       printIOMMU=1
@@ -564,6 +573,9 @@ do
      -hyperv)
 	hyperv="1"
     ;;
+     -hostaudio)
+        hostAudio="1"
+    ;;
      -romfile|-vbios)
 	romfilePath="$2"
 	shift
@@ -589,7 +601,7 @@ if [ "$printIOMMU" = "1" ]
 then
   printer "${colors[green]}Ok, printing IOMMU Groups then exiting..."
   iommuDir="/sys/kernel/iommu_groups";
-  if [ -d $iommuDir ]; then for g in `ls -1v $iommuDir`; do echo "IOMMU Group $g"; for d in $iommuDir/$g/devices/* ; do printer "${colors[cyan]}\t$(lspci -nns ${d##*/})"; done; done ; else echo "Couldn't find $iommuDir" ; fi
+  if [ -d $iommuDir ]; then for g in `ls -1v $iommuDir`; do printer "IOMMU Group $g"; for d in $iommuDir/$g/devices/* ; do printer "${colors[cyan]}\t$(lspci -nns ${d##*/})"; done; done ; else printer ${colors[red]}"Couldn't find $iommuDir" "fault" ; fi
   exit $?
 fi
 
@@ -602,7 +614,15 @@ else
 fi
 
   # Check IOMMU is active and grouping things.
-if [ -z "$(find /sys/class/iommu/ -type l)" ]; then echo -ne "IOMMU isn't loaded?\n  For an Intel machine you must add 'intel_iommu=on' to your kernel boot options in your bootloader.\n  If you're on an AMD machine instead add these two: 'iommu=pt iommu=1'\n\n  If you've already done this and rebooted, your host may not be compatible or some relevant bios settings could be disabled.\n  Feel free to ask about this in case it's a script fault.\n" ; exit 1; fi
+if [ -z "$(find /sys/class/iommu/ -type l)" ]
+then
+  printer "${colors[red]}IOMMU does not appear to be loaded?"
+  printer "\tFor an Intel machine you must add 'intel_iommu=on' to your kernel boot options in your bootloader."
+  printer "\tIf you're on an AMD machine instead add these two: 'iommu=pt iommu=1'\n"
+  printer "\tIf you've already done this and rebooted, your host may not be compatible or some relevant bios settings could be disabled."
+  printer "\tFeel free to ask about this in case it's a script fault."
+  exit 1
+fi
 
   # Determine Host cpu cores/threads and what the guest gets based on -pinvcpus (if specified).
 hostThreads=$(grep -Pom1 'siblings.*\ \K([0-9]+)$' /proc/cpuinfo )
@@ -733,28 +753,57 @@ then
   fi
 fi
 
-# Put core QEMU arguments together
+  # Put core QEMU arguments together
 
-  machineArgs="-machine q35,accel=kvm,kernel_irqchip=on" # kernel_irqchip helps prevent PCI Error Code 34 on GPUs.
-  cpuArgs="-cpu host,kvm=on,topoext=on"
+machineArgs="-machine q35,accel=kvm,kernel_irqchip=on" # kernel_irqchip helps prevent PCI Error Code 34 on GPUs.
+cpuArgs="-cpu host,kvm=on,topoext=on"
 
-  if [ ! -z "$hyperv" ]
+if [ ! -z "$hyperv" ]
+then
+  printer "${colors[green]}-hyperv\t\tspecified, HyperV Enlightenments will be enabled for this run."
+  cpuArgs+=",hv-frequencies,hv-relaxed,hv-reset,hv-runtime,hv-spinlocks=0x1fff,hv-stimer,hv-synic,hv-time,hv-vapic,hv-vpindex"
+fi
+
+smpArgs="-smp sockets=1,cores=$guestCores,threads=$guestThreads"
+coreArgs="$machineArgs -enable-kvm -m $guestmemoryMB $cpuArgs $smpArgs"
+coreArgs+=" -name $(basename $0),debug-threads=on"
+coreArgs+=" -drive if=pflash,format=raw,unit=0,readonly=on,file=$biosPath"
+coreArgs+=" -serial mon:stdio" # Add a qemu serial device
+coreArgs+=" -nodefaults"       # Don't use any default devices
+
+if [ ! -z "$hostAudio" ]
+then
+  printer "${colors[green]}-hostaudio\tspecified, VM will use a pulseaudio backend to the host for audio output this run."
+  soundArgs="-audiodev pa,id=snd0"
+  soundArgs+=" -device ich9-intel-hda -device hda-output,audiodev=snd0"
+  coreArgs+=" $soundArgs"
+
+  if ! isDry
   then
-    printer "${colors[green]}-hyperv\t\tspecified, HyperV Enlightenments will be enabled for this run."
-    cpuArgs+=",hv-frequencies,hv-relaxed,hv-reset,hv-runtime,hv-spinlocks=0x1fff,hv-stimer,hv-synic,hv-time,hv-vapic,hv-vpindex"
+    if ps -au${USER}|grep pulseaudio > /dev/null 2>&1
+    then
+      printer "${colors[green]}\t\tPulseaudio aleady running on host"
+    elif which pulseaudio
+    then
+      if pulseaudio -D
+      then
+        printer "${colors[green]}\t\tPulseaudio started on host."
+      else
+        printer "${colors[red]}\t\tFound Pulseaudio on host but could not start it."
+      fi
+    else
+      printer "${colors[red]}\tPulseaudio not found on host."
+    fi
   fi
+fi
 
-  smpArgs="-smp sockets=1,cores=$guestCores,threads=$guestThreads"
-  coreArgs="$machineArgs -enable-kvm -m $guestmemoryMB $cpuArgs $smpArgs"
-  coreArgs+=" -name $(basename $0),debug-threads=on"
-  coreArgs+=" -drive if=pflash,format=raw,unit=0,readonly=on,file=$biosPath"
-  coreArgs+=" -serial mon:stdio" # Add a qemu serial device
-  coreArgs+=" -nodefaults"       # Don't use any default devices
+
+
 if [[ ! -z "${!disks[@]}" ]]
 then
-  printer "${colors[green]}-image(s)\tspecified, using disks this run:"
+  printer "${colors[green]}-image(s)\tspecified, using virtual disk(s) this run:"
 else
-  printer "${colors[yellow]}-image\t\tnot specified, This VM will run diskless."
+  printer "${colors[yellow]}-image\t\tnot specified, This VM will run without any virtual disks."
 fi
 
 for disk in ${!disks[@]}
@@ -867,15 +916,16 @@ fi
 
 if isDry;
 then
-  echo "---------------------"
-  echo "Here are the completed args from this DRY run:"
+  printer "---------------------"
+  unset quiet
+  printer "Here are the completed args from this DRY run:"
   printer "Core:\n${colors[blue]} $coreArgs $hugeArgs"
   if [ ! -z "$networkArgs" ]; then printer "Net :\n${colors[blue]}${networkArgs}"     ; fi
   if [ ! -z "$usbArgs" ] ;    then printer "USB :\n${colors[blue]}${usbArgs}"         ; fi
   if [ ! -z "$pciArgs" ] ;    then printer "PCI :\n${colors[blue]}${pciArgs}"         ; fi
   if [ ! -z "$lgArgs" ] ;     then printer "Looking Glass:\n${colors[blue]}${lgArgs}" ; fi
   if [ ! -z "$extras" ] ;     then printer "Extras:\n${colors[blue]}${extras}"        ; fi
-  echo -ne "\nRun the script with the same arguments again and include ${colors[red]}-run${colors[none]} to actually pass these to qemu-system-x86_64\n"
+  printer "\nRun the script with the same arguments again and include ${colors[red]}-run${colors[none]} to actually pass these to qemu-system-x86_64\n"
   exit 0
 else
   sudo prlimit --pid $$ --memlock=unlimited:unlimited
@@ -888,4 +938,4 @@ else
 fi
 
 
-#Cleanup will catch on Exit
+# Cleanup will catch on Exit
