Various enumeratePCI stability and accuracy touchups.

diff --git a/main b/main
--- a/main
+++ b/main
@@ -205,7 +205,9 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
   if systemctl is-active display-manager >/dev/null && ! isDry; then systemctl stop display-manager ; export dm="seen" ; fi
 
   lspciOutput="$(lspci -nn)"
+  if [ -z "$pciREGEX" ]; then echo "pciREGEX variable is empty. Not sure how I was called? Panicing."; exit 1; fi 
   PCIDevices="$(grep -E "$pciREGEX" <<<"$lspciOutput")"
+  if [ -z "$PCIDevices" ]; then echo "Couldn't find any PCI devices with regex '$pciREGEX', please try another one. Panicing."; exit 1; fi 
   inc=0
   while read PCIDevice
   do
@@ -218,8 +220,8 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
 
     if ! [[ $@ == *"restorebind"* ]]
     then
-      currentDriver="$(lspci -nn -k -d $vendorClass | grep -oP '(?<=driver in use:\ ).*')"
-      if ! [ -z $currentDriver ]
+      currentDriver="$(lspci -nn -k -s "$buspath" | grep -oP '(?<=driver in use:\ ).*')"
+      if ! [ -z "$currentDriver" ]
       then
         deviceDrivers["$vendorClass"]="$currentDriver" # Add it to our cool array
         driver="${deviceDrivers["$vendorClass"]}"
