sudo no longer needed for dry runs; Cleanup not called when dry.
Also changed some echoed text in the PCI matcher.

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,5 +1,4 @@
 #!/bin/bash
-if [ "$EUID" -ne 0 ]; then echo "Please run me as root"; exit ; fi
 DRY=1 # Always dry unless flag '-run' is detected.
 
 
@@ -159,7 +158,7 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
   inc=0
   while read PCIDevice
   do
-    echo "  Found $PCIDevice"
+    echo "  Matched: $PCIDevice"
     buspath="0000:$(cut -d' ' -f1<<<$PCIDevice)"
 
     vendorClass="$( grep -Eo '(([0-9]|[a-f]){4}|:){3}' <<<$PCIDevice )"
@@ -280,10 +279,16 @@ done
 #|_|   |_|  \___|     |_|   |_|_|\__, |_| |_|\__|
 #                                |___/
 
-  # Set a trap to run the cleanup function.
-trap do_cleanup  EXIT HUP INT TERM
 
-if [ $DRY -eq "1" ]; then echo "This is a DRY run. Please specify -run to actually run" ; echo ; fi
+
+if [ $DRY -eq "1" ]
+then
+  echo "This is a DRY run. Please specify -run to actually run"
+else
+  if [ "$EUID" -ne 0 ]; then echo "This will not be a dry run, please use sudo."; exit 1 ; fi
+    # Set a trap to run the cleanup function.
+  trap do_cleanup  EXIT HUP INT TERM
+fi
 
   # Check for active IOMMU module.
 if ! lsmod |grep -qi iommu; then echo -ne "IOMMU isn't loaded?\n  For an Intel machine you must add 'intel_iommu=on' to your kernel boot options in your bootloader.\n  If you're on an AMD machine instead add these two: 'iommu=pt iommu=1'\n\n  If you've already done this and rebooted, your host may not be compatible or some relevant bios settings could be disabled.\n  Feel free to ask about this in case it's a script fault.\n" ; exit 1; fi
