Added a function 'isDry' to clean up the script with.

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,5 +1,5 @@
 #!/bin/bash
-DRY=1 # Always dry unless flag '-run' is detected.
+DRY=1 # Assume dry, '-run' flag will flip the bit later.
 
 
 #     _                
@@ -65,9 +65,13 @@ function printHelp {
   exit 1
 }
 
+function isDry {
+if [ $DRY -eq 1 ] ; then return 0 ; else return 1 ; fi
+}
+
 function do_cleanup {
   # Try to undo any mess we've caused
-  if [ "$DRY" -eq "0" ]
+  if ! isDry
   then
       # Undo bridge if used
     if [[ ! -z "$bridgeArgs" ]]; then bridger $bridgeArgs stop ; fi
@@ -98,14 +102,19 @@ function regexCleanup {
 }
 
 function bridger {
+  # Goal is to attach the vm's tap interface to a bridge. Creates the bridge if missing and attaches host int.
     br=$1
    int=$2 ; intMAC=$(ip link show $int|grep -Po '(?<=ether\ )([a-f]|[0-9]|\:)+')
    tap=$3
   mode=$4
 
-
-  if [ "$mode" == "start" ] && [ "$DRY" -eq "0" ]
+  if [ "$mode" == "start" ] && ! isDry
   then
+    if grep -qs -E '^up$' /sys/class/net/$br/operstate
+    then
+      echo "$br already exists and is up, going to attach to existing bridge."
+      exit 420
+    fi
     if systemctl is-active NetworkManager >/dev/null ; then systemctl stop NetworkManager ; export nm="seen" ; fi
     ip addr flush dev $int # Remove any IPs from the real int
     if ! ip link show $br  >/dev/null 2>&1; then ip link add $br type bridge     ; fi
@@ -117,10 +126,10 @@ function bridger {
     brctl show $br
     dhclient -v $br 2>&1|grep '^DHCP'
     echo ------------------
-  elif [ "$mode" == "start" ] && [ "$DRY" -eq "1" ]
+  elif [ "$mode" == "start" ] && isDry
   then
     echo "[DRY] Bridge creation skipped"
-  elif [ "$mode" == "stop" ] && [ "$DRY" -eq "0" ]
+  elif [ "$mode" == "stop" ] && ! isDry
   then
     dhclient -r $br >/dev/null 2>&1 && echo "dhclient lease released and process ended."
     for i in $tap $br; do ip link set $i down ; ip link del $i; done
@@ -130,7 +139,7 @@ function bridger {
 }
 
 function consoleDrivers { # Toggles rendering to Ctrl+Alt+F[0-9]. Needs to be unhooked for GPU passthrough.
-  if [ "$DRY" -eq "0" ]
+  if ! isDry
   then 
     if [[ "$1" -eq 'bind' ]]; then bindBoolean="1"; bindState="$1" ; else bindBoolean="0" ; bindState="unbind" ; fi
     for vtconsole in /sys/class/vtconsole/*; do echo $bindBoolean > $vtconsole/bind ; done
@@ -167,7 +176,7 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
   declare -A -g deviceDrivers # Our cool array
   if ! lsmod|grep -q vfio_pci; then modprobe vfio-pci; fi
   if [ "$?" -ne "0" ]; then echo "Could not modprove vfio-pci. Please fix this."; exit 1 ; fi
-  if systemctl is-active display-manager >/dev/null && [ "$DRY" -eq "0" ]; then systemctl stop display-manager ; export dm="seen" ; fi
+  if systemctl is-active display-manager >/dev/null && ! isDry; then systemctl stop display-manager ; export dm="seen" ; fi
 
   lspciOutput="$(lspci -nn)"
   PCIDevices="$(grep -E "$pciREGEX" <<<"$lspciOutput")"
@@ -193,24 +202,24 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
     fi
       driver="${deviceDrivers["$vendorClass"]}"
 
-    if [[ $@ == *"unbind"* ]] && [ "$DRY" -eq "0" ]
+    if [[ $@ == *"unbind"* ]] && ! isDry
     then
      echo "    Unbinding from it's driver" ; echo "$buspath" > /sys/bus/pci/devices/$buspath/driver/unbind
-    elif [[ $@ == *"unbind"* ]] && [ "$DRY" -eq "1" ]
+    elif [[ $@ == *"unbind"* ]] && isDry
     then
       echo "    [DRY] Not unbinding it"
     fi
 
-    if [[ $@ == *"vfiobind"* ]] && [ "$DRY" -eq "0" ]
+    if [[ $@ == *"vfiobind"* ]] && ! isDry
     then
       echo "    Binding it to vfio-pci" ; echo "0x$vendor 0x$class" > /sys/bus/pci/drivers/vfio-pci/new_id
       if [[ $? -ne "0" ]]; then echo "Rebind to vfio-pci failed.."; fi
       echo 1 > /sys/bus/pci/rescan
-    elif [[ $@ == *"vfiobind"* ]] && [ "$DRY" -eq "1" ]
+    elif [[ $@ == *"vfiobind"* ]] && isDry
     then
       echo "    [DRY] Not binding to vfio-pci"
       echo
-    elif [[ $@ == *"restorebind"* ]] && [ "$DRY" -eq "0" ]
+    elif [[ $@ == *"restorebind"* ]] && ! isDry
     then
       if ! [ -z "$driver" ]
       then
@@ -251,7 +260,6 @@ do
     ;;
      -huge|-hugepages)
        HUGEPAGES="1"
-       hugePath="/dev/hugepages"
     ;;
      -usb|-USB)
        usbREGEX="$2"
@@ -298,7 +306,7 @@ done
 #|_|   |_|  \___|     |_|   |_|_|\__, |_| |_|\__|
 #                                |___/
 
-if [ $DRY -eq "1" ]
+if isDry
 then
   echo "This is a DRY run. Please specify -run to actually run"
 else
@@ -349,10 +357,11 @@ else
 fi
 
   # Hugepages?
-if [ $DRY -eq "0" ]
+if ! isDry
 then
   if [  "$HUGEPAGES" == "1" ]
   then
+    hugePath="/dev/hugepages"
     Hugepagesize="$(grep Hugepagesize /proc/meminfo |grep -oE '[0-9]+')" ; HugepagesizeMB="$((( $Hugepagesize / 1024 )))"
     pagesRequired="$((($((($guestmemoryMB / $HugepagesizeMB))) + 1)))"
     echo -ne "\nHugepages enabled for this run (Pagesize=${HugepagesizeMB}MB, $pagesRequired pages deployed. for the VM's ${guestmemoryMB}MB memory.)\n"
@@ -371,11 +380,11 @@ else
   echo "-hugepages acknowledged but dry run."
 fi
 
-if [[ "$hugeMount" =~ ^(found|self)$ ]] || [ $DRY -eq "1" ]
+if [[ "$hugeMount" =~ ^(found|self)$ ]] || isDry
 then
   hugeArgs="-mem-path $hugePath"
 else
-  echo "I was unable to find or manually set up the hugepage mount. It has not been enabled for this run."
+  echo "Unable to find the hugepage mount at $hugePath. Hugepages is not enabled for this run."
 fi
  
   
@@ -433,7 +442,7 @@ if [ ! -z "$pciREGEX" ]; then consoleDrivers unbind ; enumeratePCIs unbind vfiob
 #|_|   |_|\__, |
 #         |___/
 
-if [ "$DRY" == "1" ];
+if isDry;
 then
   echo "---------------------"
   echo "Here are the completed args from this DRY run:"
