Various changes (Color, docs, script behavior)
Colorized some of the script output. (-colortest added to test this)

EFI console now only gets unbound/rebound when display-manager does.

Snippets of documentation changed.

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,5 +1,18 @@
 #!/bin/bash
 DRY=1 # Assume dry, '-run' flag will flip the bit later.
+echo "" # Professional padding
+
+# Some colors
+declare -A colors
+colors[red]="\e[31m"
+colors[green]="\e[32m"
+colors[yellow]="\e[33m"
+colors[blue]="\e[34m"
+colors[magenta]="\e[35m"
+colors[cyan]="\e[36m"
+colors[lightgray]="\e[37m"
+colors[white]="\e[97m"
+
 
 #     _                
 #  __| | ___ _ __  ___ 
@@ -72,6 +85,8 @@ if [ $DRY -eq 1 ] ; then return 0 ; else return 1 ; fi
 
 function do_cleanup {
   # Try to undo any mess we've caused
+
+  echo -ne "${colors[white]}"
   if ! isDry
   then
       # Undo bridge if used
@@ -81,9 +96,9 @@ function do_cleanup {
       # Rebind the console and PCI devices if they were rebound
     if [ ! -z "$pciREGEX" ]
     then
-      consoleDrivers bind
+      if [ ! -z "$consoleUnbound" ]; then consoleDrivers bind; fi # var only checked for zero length
       enumeratePCIs restorebind
-      if  [ "$dm" == "seen" ]; then echo "Attempting to restore your display-manager..." ; systemctl start display-manager ; fi # Start DM if seen before run.
+      if  [ "$dm" == "seen" ]; then echo "Attempting to restore display-manager..." ; systemctl start display-manager ; fi # Start DM if seen before run.
     fi
 
     if [ "$HUGEPAGES" == "1" ] # Clean up hugepages
@@ -92,6 +107,7 @@ function do_cleanup {
       if [ "$hugeMount" == "self" ]; then umount $hugePath ; fi #umount if we mounted it
     fi
   fi
+  echo -e "\n${colors[green]}Cleanup complete.${colors[white]}"
 }
 
 function regexCleanup {
@@ -141,26 +157,25 @@ function bridger {
       # Always create the tap,     attach tap to bridge,          bring tap up.
     ip tuntap add $tap mode tap && ip link set $tap master $br && ip link set $tap up
     echo '------------------'
-    echo "Bridge details:"
-    brctl show $br
-    if [ $bridgePreexists -eq 0 ]; then dhclient -v $br 2>&1|grep '^DHCP' ; else echo "Bridge already existed, not running dhclient on it" ; fi
+    echo -ne "Bridge details:\n\n" ; brctl show $br ; echo
+    if [ $bridgePreexists -eq 0 ]; then echo "Running dhclient on $br..." ; dhclient -v $br 2>&1|grep '^DHCPACK' ; else echo -e "${colors[green]}Bridge already existed, not running dhclient -r on it.${colors[white]}" ; fi
     echo '------------------'
   elif [ "$mode" == "start" ] && isDry
   then
-    echo "[DRY] Bridge creation skipped"
+    echo -e "${colors[green]}[DRY] acknowledged -bridge${colors[white]}"
   elif [ "$mode" == "stop" ] && ! isDry
   then
     if [ $bridgePreexists -eq 0 ]
     then
-      echo "Cleaning up our bridge"
-      dhclient -r $br >/dev/null 2>&1 && echo "dhcp lease released and dhclient process ended."
+      echo -e "${colors[yellow]}Cleaning up our bridge..."
+      dhclient -r $br >/dev/null 2>&1 && echo -e "${colors[green]}dhcp lease released and dhclient process ended...${colors[white]}"
       for i in $tap $br; do ip link set $i down ; ip link del $i; done # Remove the tap and bridge
-      if ! ip link show br0 >/dev/null 2>&1; then echo "Bridge is gone."; fi
+      if ! ip link show br0 >/dev/null 2>&1; then echo -e "${colors[green]}Bridge removed.${colors[white]}"; fi
     else
-      echo "We attached $tap to an existing bridge this run, removing $tap."
-      for i in $tap ; do ip link set $i down ; ip link del $i; done # Remove the tap
+      echo -e "${colors[green]}We only attached $tap to an existing bridge this run, removing $tap."
+      for i in $tap ; do ip link set $i down ; ip link del $i; done && echo -e "${colors[green]}$tap removed.${colors[white]}" # Remove the tap
     fi
-    if [ "$nm" == "seen" ]; then systemctl restart NetworkManager ; echo "NetworkManager restarted" ; fi
+    if [ "$nm" == "seen" ]; then systemctl restart NetworkManager ; echo -e "${colors[green]}NetworkManager restarted.${colors[white]}" ; fi
   fi
 }
 
@@ -170,6 +185,7 @@ function consoleDrivers { # Toggles rendering to Ctrl+Alt+F[0-9]. Needs to be un
     if [[ "$1" -eq 'bind' ]]; then bindBoolean="1"; bindState="$1" ; else bindBoolean="0" ; bindState="unbind" ; fi
     for vtconsole in /sys/class/vtconsole/*; do echo $bindBoolean > $vtconsole/bind ; done
     echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/$bindState
+    consoleUnbound=1
   fi
 }
 
@@ -189,26 +205,27 @@ function enumerateUSBs { # This only makes arguments
     then
       newUsbArg="-device usb-host,vendorid=0x$vendor,productid=0x$product"
         usbArgs="$usbArgs $newUsbArg"
-      printf "  Matched $vendor:$product as  :\t'$Name'\n    Added to USB Args as:\t$newUsbArg\n\n"
+      echo -e "  Matched: ${colors[blue]}$vendor:$product '$Name'${colors[white]}"
+      echo -e "${colors[green]}    Added to USB Args as:\t$newUsbArg\n${colors[white]}"
     else
-      printf "Skipping: '$USBDevice' as there was an issue finding it.\n"
+      echo -e "${colors[red]}Skipping: '$USBDevice' as there was an issue finding it.\n"
     fi
   done <<<"$USBDevices"
 }
 
 function enumeratePCIs { # This makes arguments and also unbinds from drivers. Optional vfio-pci rebinding.
   function gpuDetectedAndInUse {
-    echo "Video device $1 appears to be in use by the host (Display-manager, efi-framebuffer[virtual consoles] or otherwise)."
-    echo "At the current time I'll need to stop your display manager to continue."
-    echo "If you don't think the host is using this [RIGHT NOW] then there may be an error."
+    echo -e "${colors[yellow]}Video device $1 appears to be in use by the host (Display-manager, efi-framebuffer[virtual consoles] or otherwise).${colors[white]}"
+    echo -e "${colors[yellow]}At the current time I'll need to stop your display manager to continue.${colors[white]}"
+    echo -e "${colors[yellow]}If you don't think the host is using this [RIGHT NOW] then there may be an error.${colors[white]}"
     if systemctl is-active display-manager >/dev/null && ! isDry
     then
-      echo "Stopping display-manager and unbinding console drivers in 5 seconds..." ; sleep 5
+      echo -e "${colors[yellow]}Stopping display-manager and unbinding console drivers in 5 seconds...${colors[white]}" ; sleep 5
       systemctl stop display-manager ; export dm="seen"
     else
-      echo "Could not find a service for display-manager."
+      echo -e "${colors[yellow]}Could not find a service for display-manager.${colors[white]}"
     fi
-    consoleDrivers unbind && echo "Console drivers unbound, host may be headless"
+    consoleDrivers unbind && echo -e "${colors[yellow]} Console drivers unbound, host may be headless"
   }
 
   echo "PCI:"
@@ -223,7 +240,7 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
   inc=0
   while read PCIDevice
   do
-    echo "  Matched: $PCIDevice"
+    echo -e "  Matched: ${colors[blue]}$PCIDevice"
     shortBuspath="$(cut -d' ' -f1<<<$PCIDevice)"
     buspath="0000:$shortBuspath"
 
@@ -238,7 +255,7 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
       then
         deviceDrivers["$vendorClass"]="$currentDriver" # Add it to our cool array
         driver="${deviceDrivers["$vendorClass"]}"
-        echo "   [INFO] Driver is '$driver' and will be rebound on VM exit"
+        echo -e "    ${colors[green]}[INFO] Detected driver '$driver' is using this device. It will be re-bound on VM exit.${colors[white]}"
       fi
     fi
       driver="${deviceDrivers["$vendorClass"]}"
@@ -246,29 +263,29 @@ function enumeratePCIs { # This makes arguments and also unbinds from drivers. O
     if [[ $@ == *"unbind"* ]] && ! isDry
     then
       if ! isDry && grep -o '\[VGA controller\]' <<<$(lspci -vnnn -s "$buspath") ; then gpuDetectedAndInUse "$busPath[$vendorClass]" ; fi
-      echo "    Unbinding from it's driver" ; echo "$buspath" > /sys/bus/pci/devices/$buspath/driver/unbind
+      echo -e "${colors[green]}    Unbinding from:\t${colors[white]}$driver" ; echo "$buspath" > /sys/bus/pci/devices/$buspath/driver/unbind
     elif [[ $@ == *"unbind"* ]] && isDry
     then
-      echo "    [DRY] Not unbinding it"
+      echo -e "    ${colors[green]}[DRY]  Not unbinding it.${colors[white]}"
     fi
 
     if [[ $@ == *"vfiobind"* ]] && ! isDry
     then
-      echo "    Binding it to vfio-pci" ; echo "0x$vendor 0x$class" > /sys/bus/pci/drivers/vfio-pci/new_id
-      if [ $? -ne 0 ]; then echo "Rebind to vfio-pci failed.."; fi
+      echo -e "${colors[green]}    Binding to:\t\t${colors[white]}vfio-pci" ; echo "0x$vendor 0x$class" > /sys/bus/pci/drivers/vfio-pci/new_id
+      if [ $? -ne 0 ]; then echo -e "    ${colors[red]}Rebind to vfio-pci failed!"; fi
       echo 1 > /sys/bus/pci/rescan
     elif [[ $@ == *"vfiobind"* ]] && isDry
     then
-      echo "    [DRY] Not binding to vfio-pci"
+      echo -e "    ${colors[green]}[DRY]  Not binding to:\t${colors[white]}vfio-pci"
       echo
     elif [[ $@ == *"restorebind"* ]] && ! isDry
     then
       if ! [ -z "$driver" ]
       then
-        echo "    Rebinding $vendorClass to driver: $driver"
+        echo -e "${colors[green]}    Rebinding $vendorClass to driver:\t${colors[white]}$driver"
 	echo "$buspath" > /sys/bus/pci/devices/$buspath/driver/unbind
 	echo "$buspath" > /sys/bus/pci/drivers/$driver/bind
-	if [ "$?" -eq "0" ]; then echo "$vendorClass successfully rebound to $driver" ; fi
+	if [ "$?" -eq "0" ]; then echo -e "${colors[green]}    Successfully rebound to:\t\t${colors[white]}$driver" ; else echo -e "${colors[red]}    Was unable to rebind it to $driver."; fi
       fi
     fi
 
@@ -292,6 +309,11 @@ if [[ -z "$@" ]] ; then echo "No args seen. Printing help" ; printHelp ; fi
 while [ $# -gt 0 ]
 do
   case "$1" in
+    -colortest|-colourtest)
+       echo "Ok, doing a color test then exiting..."
+       for i in $(sort <<< ${!colors[@]}) ; do echo -e "Test for: ${colors[$i]}$i ${colors[white]}" ; done
+       exit 0
+    ;;
     -bridge|-BRIDGE)
        bridgeArgs="$(sed 's/,/ /g' <<<$2)"
        shift
@@ -355,7 +377,7 @@ done
 
 if isDry
 then
-  echo "This is a DRY run. Please specify -run to actually run"
+  echo -e "${colors[magenta]}This is a DRY run. Please specify ${colors[red]}-run${colors[magenta]} to actually run${colors[white]}"
 else
   if [ "$EUID" -ne 0 ]; then echo "This will not be a dry run, please use sudo."; exit 1 ; fi
     # Set a trap to run the cleanup function.
@@ -373,11 +395,11 @@ hostThreads=$(grep -Pom1 'siblings.*\ \K([0-9]+)$' /proc/cpuinfo )
 if [ -z "$taskset" ]
 then
   guestCores=$hostCores ; if [ ! -z $hostIsThreaded ]; then guestThreads=2; else guestThreads=1; fi
-  echo "-taskset not specified, using all host cores: ($hostCores) with ($hostThreads) threads."
+  echo -e "${colors[yellow]}-taskset not specified, guest gets full host CPU:\t${colors[white]} ($hostCores) with ($hostThreads) threads."
 else
   if grep -qE '^([0-9]|,)+$' <<< $tasksetThreads
   then
-    echo "-taskset specified.. This run will limiting the guest to using host CPU threads: $tasksetThreads"
+    echo -e "${colors[green]}-taskset specified. Guest will run on host CPU threads:\t$tasksetThreads${colors[white]}"
     OLDIFS="$IFS" ; IFS=, ; tasksetCount=$(echo $tasksetThreads| wc -w) ; IFS="$OLDIFS"
       # Check if specified -taskset thread count is divisible by 2. Use hyperthreading/smt if supported
     if (( $tasksetCount % 2 == 0 )) && [ "$hostIsThreaded" == "1" ] ; then guestCores=$((( $tasksetCount / 2 ))) ; guestThreads=2; else guestCores=$tasksetCount ; guestThreads=1 ; fi
@@ -389,69 +411,61 @@ fi
   # Determine guest memory
 if [ -z "$memoryArgs" ]
 then
-  echo -ne "-memory argument not provided, will use half of host: "
   totalHostMemoryKB=$(grep -oPm1 '(?!=MemTotal\:(\ )+)[0-9]+' /proc/meminfo)
   if [ ! -z "$totalHostMemoryKB" ]
   then
     guestmemoryMB="$((($totalHostMemoryKB / 1024 / 2)))"
-    echo -ne "$guestmemoryMB\n"
+    echo -e "${colors[yellow]}-memory argument missing, will use half host total:\t${colors[white]} ${guestmemoryMB} MB${colors[white]}"
   else
-    echo "Failed to find a default memory value for the guest."
+    echo "${colors[red]}Failed to find a default memory value for the guest.${colors[white]}"
   fi
 else
   if  [[ "$memoryArgs" =~ 'G' ]]; then memoryArgs="$((($(grep -Eo '[0-9]+' <<< $memoryArgs) * 1024 )))"; fi # Convert to MB
   guestmemoryMB=$memoryArgs
 fi
 
-  # Hugepages?
-if ! isDry
-then
-  if [  "$HUGEPAGES" == "1" ]
-  then
-    hugePath="/dev/hugepages"
-    Hugepagesize="$(grep Hugepagesize /proc/meminfo |grep -oE '[0-9]+')" ; HugepagesizeMB="$((( $Hugepagesize / 1024 )))"
-    pagesRequired="$((($((($guestmemoryMB / $HugepagesizeMB))) + 1)))"
-    echo -ne "\nHugepages enabled for this run (Pagesize=${HugepagesizeMB}MB, $pagesRequired pages deployed. for the VM's ${guestmemoryMB}MB memory.)\n"
-    if grep -q "$hugePath" /proc/mounts
-    then
-      hugeMount=found
-    else
-      echo "/dev/hugepages not mounted, mounting."
-      mount -t hugetlbfs hugetlbfs -o mode=01770,gid=0 $hugePath && hugeMount=self # So we can umount later
-    fi
-    echo "$pagesRequired" > /proc/sys/vm/nr_hugepages ; echo -ne "Giving hugepages a moment to allocate...\n" ; sleep 3
-    HugePages_Total="$(grep HugePages_Total /proc/meminfo | grep -Eo '[0-9]+')"
-    if [[ "$HugePages_Total" -lt "$pagesRequired" ]]; then echo -ne "Error, couldn't allocate all required pages. Please free up memory or check your system.\n\t($HugePages_Total pages allocated out of $pagesRequired. With that the best we can do is: -mem $((($HugePages_Total * HugepagesizeMB))))\n"; exit 1 ; fi
- fi
-else
-  echo "-hugepages acknowledged but dry run."
-fi
-
-if [[ "$hugeMount" =~ ^(found|self)$ ]] || isDry
-then
-  hugeArgs="-mem-path $hugePath"
-else
-  echo "Unable to find the hugepage mount at $hugePath. Hugepages is not enabled for this run."
-fi
- 
-  
-
-
-  # Make the bridge
-if [[ ! -z "$bridgeArgs" ]]; then bridger start $bridgeArgs ; fi
-
-  # Evaulate biosPath
+  # Eval biosPath
 if [[ -z "$biosPath" ]]
 then
   defaultBiosPath="/usr/share/ovmf/x64/OVMF_CODE.fd"
   if [[ ! -f "$defaultBiosPath" ]]
   then
-    echo "-bios argument not provided and couldn't find default '$defaultBiosPath'. Please install OVMF or set your .fd file with the -bios argument"
+    echo -e "${colors[red]}-bios argument missing and couldn't find default '$defaultBiosPath'. Please install OVMF or set your .fd file with the -bios argument"
   else
-    echo "-bios argument not provided, using discovered default: $defaultBiosPath"
+    echo -e "${colors[green]}-bios argument missing, using discovered default:\t${colors[white]} ${defaultBiosPath}"
     biosPath=$defaultBiosPath
   fi
 fi
+
+# Eval Hugepages
+hugePath="/dev/hugepages"
+if [  "$HUGEPAGES" == "1" ] && ! isDry
+then
+  Hugepagesize="$(grep Hugepagesize /proc/meminfo |grep -oE '[0-9]+')" ; HugepagesizeMB="$((( $Hugepagesize / 1024 )))"
+  pagesRequired="$((($((($guestmemoryMB / $HugepagesizeMB))) + 1)))"
+  echo -ne "\nHugepages enabled for this run (Pagesize=${HugepagesizeMB}MB, $pagesRequired pages deployed. for the VM's ${guestmemoryMB}MB memory.)\n"
+  if grep -q "$hugePath" /proc/mounts
+  then
+    hugeMount=found && hugeArgs="-mem-path $hugePath"
+  else
+    echo "/dev/hugepages not mounted, attempting to mount it."
+    mount -t hugetlbfs hugetlbfs -o mode=01770,gid=0 $hugePath && hugeMount=self && hugeArgs="-mem-path $hugePath" # So we can umount later
+  fi
+  echo "$pagesRequired" > /proc/sys/vm/nr_hugepages ; echo -ne "Giving hugepages a moment to allocate...\n" ; sleep 3
+  HugePages_Total="$(grep HugePages_Total /proc/meminfo | grep -Eo '[0-9]+')"
+  if [[ "$HugePages_Total" -lt "$pagesRequired" ]]; then echo -ne "Error, couldn't allocate all required pages. Please free up memory or check your system.\n\t($HugePages_Total pages allocated out of $pagesRequired. With that the best we can do is: -mem $((($HugePages_Total * HugepagesizeMB))))\n"; exit 1 ; fi
+elif isDry
+  then
+  echo -e "${colors[green]}[DRY] acknowledged -hugepages${colors[white]}"
+fi
+
+if [  "$HUGEPAGES" == "1" ] && [ -z "$hugeMount" ] && ! isDry
+then
+  echo -e "${colors[red]}Unable to find the hugepage mount at $hugePath. Hugepages is not enabled for this run.${colors[white]}"
+fi
+ 
+  # Make the bridge
+if [[ ! -z "$bridgeArgs" ]]; then bridger start $bridgeArgs ; fi
 
 echo
 
@@ -463,7 +477,7 @@ echo
   smpArgs="-smp sockets=1,cores=$guestCores,threads=$guestThreads"
   coreArgs="$machineArgs -enable-kvm -m $guestmemoryMB $cpuArgs $smpArgs"
   if [ ! -z "$image" ] && [ ! -z "$imageFormat" ]; then image="$image,format=$imageFormat" ; fi
-  if [ ! -z "$image" ] ; then coreArgs="$coreArgs -drive file=$image,id=disk" ; else echo "You have not specified a disk image with -image, this VM will have no disk this run" ; fi
+  if [ ! -z "$image" ] ; then coreArgs="$coreArgs -drive file=$image,id=disk" ; else echo -e "${colors[yellow]}You have not specified a disk image with -image, this VM will have no disk this run${colors[white]}\n" ; fi
   coreArgs="$coreArgs -bios $biosPath"
     if [ ! -z $iso  ]  ;then coreArgs="$coreArgs -cdrom $iso" ; fi
     if [[ ! -z "$usbREGEX" ]] && [[ ! -z "$pciREGEX" ]] || [[ -z "$DISPLAY" ]] ; then coreArgs="$coreArgs -nographic -vga none" ; fi # Create X11 window if no passthrough used. Also if $DISPLAY isn't set.
@@ -494,14 +508,15 @@ if isDry;
 then
   echo "---------------------"
   echo "Here are the completed args from this DRY run:"
-  echo "Core: $coreArgs $hugeArgs"
-  echo "Net : $networkArgs"
-  echo "USB : $usbArgs"
-  echo "PCI : $pciArgs"
+  echo -e "Core:\n${colors[blue]} $coreArgs $hugeArgs${colors[white]}"
+  echo -e "Net :\n${colors[blue]} $networkArgs${colors[white]}"
+  echo -e "USB :\n${colors[blue]} $usbArgs${colors[white]}"
+  echo -e "PCI :\n${colors[blue]}$pciArgs${colors[white]}"
   if [ ! -z "$taskset" ]; then echo "Taskset parms: $taskset"; fi
-  echo -ne "\nRun the same command again but with '-run' to actually pass these to qemu-system-x86_64\n"
+  echo -ne "\nRun the script with the same arguments again and include ${colors[red]}-run${colors[white]} to actually pass these to qemu-system-x86_64\n"
   exit 0
 else
+  echo -ne "Starting qemu now.\n\n"
   $taskset qemu-system-x86_64 $coreArgs $hugeArgs $networkArgs $usbArgs $pciArgs
 fi
 
